const dataPhoto = [
    {
        name: "Cắt mí ",
        link: "#cat-mi",
        img: [
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/tui-nguc-gel-silicon-the-he-moi.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/tui-nguc-gel-silicon-the-he-moi.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/nang-nguc-dat-tui-silicon-lac-hau-khong-dam-bao-an-toan.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/nang-nguc-dat-tui-silicon-lac-hau-khong-dam-bao-an-toan.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/tui-nguc-silicon.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/tui-nguc-silicon.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/tui-nguc-silicon-long.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/tui-nguc-silicon-long.jpg",
            },
        ],
    },
    {
        name: "Nâng mũi ",
        link: "#nang-mui",
        img: [
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
            },
        ],
    },
    {
        name: "Nâng ngực ",
        link: "#nang-nguc",
        img: [
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
            },
        ],
    },
    {
        name: "Trẻ hóa da ",
        link: "#tre-hoa-da",
        img: [
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
            },
        ],
    },
    {
        name: "Trị nám, tàn nhang ",
        link: "#tri-nam-tan-nhang",
        img: [
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
            },
        ],
    },
    {
        name: "Tiêm filler/botox ",
        link: "#tiem-filler-botox",
        img: [
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
            },
        ],
    },
    {
        name: "Hút mỡ ",
        link: "#hut-mo",
        img: [
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
            },
        ],
    },
    {
        name: "Cấy mỡ ",
        link: "#cay-mo",
        img: [
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
            },
        ],
    },
    {
        name: "Thẩm mỹ hàm mặt ",
        link: "#tham-my-ham-mat",
        img: [
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
            },
        ],
    },
    {
        name: "Trị mụn ",
        link: "#tri-mun",
        img: [
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
            },
        ],
    },
    {
        name: "Trị sẹo ",
        link: "#tri-seo",
        img: [
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
            },
        ],
    },
    {
        name: "Phun xăm ",
        link: "#phun-xam",
        img: [
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
            },
        ],
    },
    {
        name: "Triệt lông ",
        link: "#triet-long",
        img: [
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
            },
        ],
    },
    {
        name: "Trị thâm ",
        link: "#tri-tham",
        img: [
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic4.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic3.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic2.jpg",
            },
            {
                small:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
                large:
                    "https://benhvienthammydonga.vn/wp-content/uploads/2023/01/pic1.jpg",
            },
        ],
    },
];