const dataDoctor = [
    {
        id: "1",
        name: "DR. Felix Trần",
        position: " Giám đốc chuyên môn phẫu thuật Bệnh viện thẩm mỹ Đông Á",
        image:
            "https://benhvienthammydonga.vn/wp-content/uploads/2023/02/bs-felix-tran.png",
        category: "Phẫu thuật thẩm mỹ",
        showHome: "true",
        imageRegion: "none",
        description:
            "<ul>\n<li>- Thành viên Hiệp hội thẩm mỹ và tái tạo gương mặt Hàn Quốc (KAFPRS)</li>\n<li>- Thành viên Hội phẫu thuật tạo hình &#8211; Thẩm mỹ Việt Nam (VSAPS)</li>\n<li>- Thành viên Hội phẫu thuật thẩm mỹ Châu Á &#8211; Thái Bình Dương</li>\n</ul>\n",
        dataModal:
            '<ul>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--1"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">chức vụ</span>\n    </li>\n<li>Giám đốc chuyên môn phẫu thuật Bệnh viện thẩm mỹ Đông Á</li>\n<li>Thành viên Hiệp hội thẩm mỹ và tái tạo gương mặt Hàn Quốc (KAFPRS)</li>\n<li>Thành viên Hội phẫu thuật tạo hình &#8211; Thẩm mỹ Việt Nam (VSAPS)</li>\n<li>Thành viên Hội phẫu thuật thẩm mỹ Châu Á &#8211; Thái Bình Dương</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--2"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">quá trình học tập và công tác</span>\n    </li>\n<li>1994-2000:Tốt nghiệp Bác sĩ đa khoa Đại học Y Dược HCM</li>\n<li>2001-2003: Hoàn thành khóa học phẫu thuật hút mỡ Vaserlipo – Newport Beach, California, Hoa Kỳ.</li>\n<li>2004 -2005: Hoàn thành khóa học Thẩm mỹ và tái tạo gương mặt- Tập đoàn Coco Plastic Hàn Quốc</li>\n<li>2009 &#8211; 2011: Tốt nghiệp chuyên khoa cấp 1 trường Đại học Y dược thành phố Hồ Chí Minh</li>\n<li>Chứng chỉ chuyên khoa cấp 1 chấn thương chỉnh hình</li>\n<li>Chứng chỉ chuyên khoa tạo hình thẩm mỹ &#038; hàm mặt</li>\n<li>2012- nay: Bác sĩ phẫu thuật thẩm mỹ tại Bệnh viện Thẩm mỹ Đông Á</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--3"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">kinh nghiệm làm việc</span>\n    </li>\n<li>5 năm kinh nghiệm trong lĩnh vực ngoại khoa</li>\n<li>8 năm kinh nghiệm Phẫu thuật tạo hình thẩm mỹ gương mặt</li>\n<li>7 năm kinh nghiệm Phẫu thuật nâng mũi, cắt mí, nâng ngực, hút mỡ</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--4"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">các dịch vụ thẩm mỹ thực hiện</span>\n    </li>\n<li>Phẫu thuật cắt mí, phẫu thuật nâng mũi, sửa mũi hỏng, mũi dị tật bẩm sinh</li>\n<li>Phẫu thuật Nâng ngực bằng phương pháp nội soi</li>\n<li>Phẫu tthuật treo sa trễ, cắt tuyến vú, thu nhỏ quầng vú, đầu ti</li>\n<li>Hút mỡ và Phẫu thuật tạo hình thành bụng bằng phương pháp siêu âm</li>\n<li>Phẫu thuật tạo hình thành bụng: Tạo hình thành bụng mini, toàn phần.</li>\n<li>Phẫu thuật hút cấy mỡ: Hút mỡ, cấy mỡ tạo hình đường nét cơ thể.</li>\n</ul>\n',
    },
    {
        id: "2",
        name: "BS Kevin Phạm",
        position:
            " Bác sĩ chuyên khoa Phẫu thuật tạo hình - Thẩm mỹ Bệnh viện thẩm mỹ Đông Á",
        image:
            "https://benhvienthammydonga.vn/wp-content/uploads/2023/02/bs-kevin-pham.png",
        category: "Phẫu thuật thẩm mỹ",
        showHome: "true",
        imageRegion: "none",
        description:
            "<ul>\n<li>Thành viên Hiệp hội thẩm mỹ tái tạo gương mặt Hàn Quốc KAFPRS</li>\n<li>Thành viên Hiệp hội thẩm mỹ Hàn Quốc KCCS</li>\n<li>Ủy viên hội nghiên cứu chỉnh hình mũi &#8211; Hiệp hội chỉnh hình Hàn Quốc</li>\n</ul>\n",
        dataModal:
            '<ul>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--1"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">chức vụ</span>\n    </li>\n<li>Bác sĩ chuyên khoa Phẫu thuật tạo hình &#8211; Thẩm mỹ Bệnh viện thẩm mỹ Đông Á</li>\n<li>Thành viên Hiệp hội thẩm mỹ tái tạo gương mặt Hàn Quốc KAFPRS</li>\n<li>Thành viên Hiệp hội thẩm mỹ Hàn Quốc KCCS</li>\n<li>Ủy viên hội nghiên cứu chỉnh hình mũi &#8211; Hiệp hội chỉnh hình Hàn Quốc</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--2"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">quá trình học tập và công tác</span>\n    </li>\n<li>2005-2012: Tốt nghiệp Bác sĩ đa khoa &#8211; Đại học Y Hải Phòng</li>\n<li>2012-2015: Hoàn thành khóa học Phẫu thuật tạo hình gương mặt &#8211; Hiệp hội thẩm mỹ Hàn Quốc KCCS</li>\n<li>2015-2016: Hoàn thành khóa học phẫu thuật nâng mũi cấu trúc &#8211;  Tập đoàn Coco Plastic Hàn Quốc</li>\n<li>2017-2018: Hoàn thành khóa học phẫu thuật tạo hình vi phẫu &#8211; tại Hiệp hội thẩm mỹ và tái tạo gương mặt Hàn Quốc KAFPRS</li>\n<li>2015-nay: Chuyên gia phẫu thuật thẩm mỹ tạo hình gương mặt cấp cao tại Bệnh viện thẩm mỹ Đông Á</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--3"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">kinh nghiệm làm việc</span>\n    </li>\n<li>3 năm kinh nghiệm trong lĩnh vực thẩm mỹ tạo hình gương mặt cùng các chuyên gia của Hiệp hội thẩm mỹ tái tạo gương mặt Hàn Quốc KAFPRS</li>\n<li>5 năm kinh nghiệm trong lĩnhvực chỉnh hình mắt mũi cùng chuyên gia Tập đoàn Coco Plastic Hàn Quốc </li>\n<li>7 năm kinh nghiệm phẫu thuật thẩm mỹ ( mắt, mũi, hàm mặt, &#8230;) và dị tật bẩm sinh vùng đầu &#8211; mặt- cổ cùng chuyên gia</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--4"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">các dịch vụ thẩm mỹ thực hiện</span>\n    </li>\n<li>Phẫu thuật dị tật bẩm sinh vùng đầu – cổ, dị tật tai nhỏ, phẫu thuật vi phẫu bàn tay, phẫu thuật di chứng bỏng, sứt môi, hở hàm ếch, dị tật sọ mặt phức tạp, chấn thương ổ mắt…</li>\n<li>Phẫu thuật cắt mí lấy bỏ da mỡ thừa, phục hồi cơ nâng mi sa trễ mi phức tạp kĩ thuật cao. Lấy bọng mỡ, căng da mí dưới. Phẫu thuật sửa mí hỏng.</li>\n<li>Phẫu thuật thẩm mỹ mũi: Nâng mũi cấu trúc dựng trụ mũi + nâng sống mũi silicone bọc sụn tai + Sửa đầu mũi + Thu nhỏ cánh mũi + Phẫu thuật tạo hình thẩm mỹ mũi khó dị tật biến dạng và sau chấn thương.</li>\n<li>Phẫu thuật cấy mỡ toàn mặt + căng chỉ trẻ hóa khuôn mặt toàn diện.</li>\n<li>Phẫu thuật tạo hình môi: Phẫu thuật cắt niêm mạc vùng hàm môi trên điều trị cười hở lợi, Tạo hình môi trái tim, sa trễ môi dưới.</li>\n<li>Phẫu thuật thẩm mỹ vùng kín.</li>\n</ul>\n',
    },
    {
        id: "3",
        name: "BS Henry Nguyen",
        position:
            " Bác sĩ chuyên khoa Phẫu thuật tạo hình - Thẩm mỹ Bệnh viện thẩm mỹ Đông Á",
        image:
            "https://benhvienthammydonga.vn/wp-content/uploads/2023/02/bs-henry-nguyen.png",
        category: "Phẫu thuật thẩm mỹ",
        showHome: "true",
        imageRegion: "none",
        description:
            "<ul>\n<li>Thành viên Hiệp hội thẩm mỹ tái tạo gương mặt Hàn Quốc KAFPRS</li>\n<li>Thành viên Hiệp hội thẩm mỹ Hàn Quốc KCCS</li>\n<li>Ủy viên hội nghiên cứu chỉnh hình mũi &#8211; Hiệp hội chỉnh hình Hàn Quốc</li>\n</ul>\n",
        dataModal:
            '<ul>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--1"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">chức vụ</span>\n    </li>\n<li>Bác sĩ chuyên khoa Phẫu thuật tạo hình &#8211; Thẩm mỹ Bệnh viện thẩm mỹ Đông Á</li>\n<li>Thành viên Hiệp hội thẩm mỹ tái tạo gương mặt Hàn Quốc KAFPRS</li>\n<li>Thành viên Hiệp hội thẩm mỹ Hàn Quốc KCCS</li>\n<li>Ủy viên hội nghiên cứu chỉnh hình mũi &#8211; Hiệp hội chỉnh hình Hàn Quốc</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--2"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">quá trình học tập và công tác</span>\n    </li>\n<li>2003-2010: Tốt nghiệp Bác sĩ đa khoa &#8211; Đại học Y Hà Nội</li>\n<li>2010-2014: Hoàn thành khóa học Phẫu thuật tạo hình gương mặt &#8211; Hiệp hội thẩm mỹ Hàn Quốc KCCS</li>\n<li>2014-2016: Hoàn thành khóa học phẫu thuật nâng mũi cấu trúc &#8211;  Tập đoàn Coco Plastic Hàn Quốc</li>\n<li>2017-2018: Hoàn thành khóa học phẫu thuật tạo hình vi phẫu &#8211; Hội phẫu thuật thẩm mỹ và y học Hàn Quốc</li>\n<li>2013-nay: Chuyên gia phẫu thuật thẩm mỹ tạo hình gương mặt cấp cao tại Bệnh viện thẩm mỹ Đông Á</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--3"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">kinh nghiệm làm việc</span>\n    </li>\n<li>5 năm kinh nghiệm trong lĩnh vực thẩm mỹ tạo hình gương mặt cùng các chuyên gia của Hội phẫu thuật thẩm mỹ và y học Hàn Quốc</li>\n<li>5 năm kinh nghiệm trong lĩnhvực chỉnh hình mắt mũi cùng chuyên gia Tập đoàn Coco Plastic Hàn Quốc </li>\n<li>9 năm kinh nghiệm phẫu thuật thẩm mỹ ( mắt, mũi, hàm mặt, &#8230;) và dị tật bẩm sinh vùng đầu &#8211; mặt- cổ cùng chuyên gia</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--4"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">các dịch vụ thẩm mỹ thực hiện</span>\n    </li>\n<li>Phẫu thuật dị tật bẩm sinh vùng đầu – cổ, dị tật tai nhỏ, phẫu thuật vi phẫu bàn tay, phẫu thuật di chứng bỏng, sứt môi, hở hàm ếch, dị tật sọ mặt phức tạp, chấn thương ổ mắt…</li>\n<li>Phẫu thuật cắt mí lấy bỏ da mỡ thừa, phục hồi cơ nâng mi sa trễ mi phức tạp kĩ thuật cao. Lấy bọng mỡ, căng da mí dưới. Phẫu thuật sửa mí hỏng.</li>\n<li>Phẫu thuật thẩm mỹ mũi: Nâng mũi cấu trúc dựng trụ mũi + nâng sống mũi silicone bọc sụn tai + Sửa đầu mũi + Thu nhỏ cánh mũi + Phẫu thuật tạo hình thẩm mỹ mũi khó dị tật biến dạng và sau chấn thương.</li>\n<li>Phẫu thuật cấy mỡ toàn mặt + căng chỉ trẻ hóa khuôn mặt toàn diện.</li>\n<li>Phẫu thuật tạo hình môi: Phẫu thuật cắt niêm mạc vùng hàm môi trên điều trị cười hở lợi, Tạo hình môi trái tim, sa trễ môi dưới.</li>\n<li>Phẫu thuật thẩm mỹ vùng kín.</li>\n</ul>\n',
    },
    {
        id: "4",
        name: "BS Raymond Dan",
        position:
            " Bác sĩ chuyên khoa Phẫu thuật tạo hình - Thẩm mỹ Bệnh viện thẩm mỹ Đông Á",
        image:
            "https://benhvienthammydonga.vn/wp-content/uploads/2023/02/bs-raymond-dan.png",
        category: "Phẫu thuật thẩm mỹ",
        showHome: "true",
        imageRegion: "none",
        description:
            "<ul>\n<li>Thành viên Hiệp hội thẩm mỹ tái tạo gương mặt Hàn Quốc</li>\n<li>Thành viên Hiệp hội thẩm mỹ Hàn Quốc KCCS</li>\n<li>Ủy viên hội nghiên cứu chỉnh hình mũi &#8211; Hiệp hội chỉnh hình Hàn Quốc</li>\n</ul>\n",
        dataModal:
            '<ul>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--1"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">chức vụ</span>\n    </li>\n<li>Bác sĩ chuyên khoa Phẫu thuật tạo hình &#8211; Thẩm mỹ Bệnh viện thẩm mỹ Đông Á</li>\n<li>Thành viên Hiệp hội thẩm mỹ tái tạo gương mặt Hàn Quốc</li>\n<li>Thành viên Hiệp hội thẩm mỹ Hàn Quốc KCCS</li>\n<li>Ủy viên hội nghiên cứu chỉnh hình mũi &#8211; Hiệp hội chỉnh hình Hàn Quốc</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--2"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">quá trình học tập và công tác</span>\n    </li>\n<li>2005-2012: Tốt nghiệp Bác sĩ đa khoa &#8211; Đại học Y Tây Nguyên</li>\n<li>2012-2015: Hoàn thành khóa học Phẫu thuật tạo hình gương mặt &#8211; Hiệp hội thẩm mỹ Hàn Quốc KCCS</li>\n<li>2015-2018: Hoàn thành khóa học phẫu thuật tạo hình vi phẫu &#8211; tại Tổ chức giải phẫu thẩm mỹ Hàn Quốc</li>\n<li>2017-nay: Chuyên gia phẫu thuật thẩm mỹ tạo hình gương mặt cấp cao tại Bệnh viện thẩm mỹ Đông Á</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--3"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">kinh nghiệm làm việc</span>\n    </li>\n<li>5 năm kinh nghiệm trong lĩnh vực thẩm mỹ tạo hình gương mặt cùng các chuyên gia Tập đoàn Coco Plastic Hàn Quốc ,chuyên gia của Hiệp hội thẩm mỹ tái tạo gương mặt Hàn Quốc</li>\n<li>9 năm kinh nghiệm phẫu thuật thẩm mỹ ( mắt, mũi, hàm mặt, &#8230;) và dị tật bẩm sinh vùng đầu &#8211; mặt- cổ cùng chuyên gia</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--4"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">các dịch vụ thẩm mỹ thực hiện</span>\n    </li>\n<li>Phẫu thuật dị tật bẩm sinh vùng đầu – cổ, dị tật tai nhỏ, phẫu thuật vi phẫu bàn tay, phẫu thuật di chứng bỏng, sứt môi, hở hàm ếch, dị tật sọ mặt phức tạp, chấn thương ổ mắt…</li>\n<li>Phẫu thuật cắt mí lấy bỏ da mỡ thừa, phục hồi cơ nâng mi sa trễ mi phức tạp kĩ thuật cao. Lấy bọng mỡ, căng da mí dưới. Phẫu thuật sửa mí hỏng.</li>\n<li>Phẫu thuật thẩm mỹ mũi: Nâng mũi cấu trúc dựng trụ mũi + nâng sống mũi silicone bọc sụn tai + Sửa đầu mũi + Thu nhỏ cánh mũi + Phẫu thuật tạo hình thẩm mỹ mũi khó dị tật biến dạng và sau chấn thương.</li>\n<li>Phẫu thuật cấy mỡ toàn mặt + căng chỉ trẻ hóa khuôn mặt toàn diện.</li>\n<li>Phẫu thuật tạo hình môi: Phẫu thuật cắt niêm mạc vùng hàm môi trên điều trị cười hở lợi, Tạo hình môi trái tim, sa trễ môi dưới.</li>\n<li>Phẫu thuật thẩm mỹ vùng kín.</li>\n</ul>\n',
    },
    {
        id: "5",
        name: "BS Robert Nguyen",
        position:
            " Bác sĩ chuyên khoa Phẫu thuật Tạo hình vóc dáng - Bệnh viện Thẩm mỹ Đông Á",
        image:
            "https://benhvienthammydonga.vn/wp-content/uploads/2023/02/bs-robert-nguyen.png",
        category: "Phẫu thuật thẩm mỹ",
        showHome: "true",
        imageRegion: "none",
        description:
            "<ul>\n<li>Thành viên Hiệp hội Tạo hình &#8211; Thẩm mỹ Hàn Quốc</li>\n<li>Thành viên Hiệp hội thẩm mỹ Hàn Quốc KCCS</li>\n<li>Thành viên Hội phẫu thuật thẩm mỹ Châu Á &#8211; Thái Bình Dương</li>\n</ul>\n",
        dataModal:
            '<ul>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--1"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">chức vụ</span>\n    </li>\n<li>Bác sĩ chuyên khoa Phẫu thuật Tạo hình vóc dáng &#8211; Bệnh viện Thẩm mỹ Đông Á</li>\n<li>Thành viên Hiệp hội Tạo hình &#8211; Thẩm mỹ Hàn Quốc</li>\n<li>Thành viên Hiệp hội thẩm mỹ Hàn Quốc KCCS</li>\n<li>Thành viên Hội phẫu thuật thẩm mỹ Châu Á &#8211; Thái Bình Dương</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--2"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">quá trình học tập và công tác</span>\n    </li>\n<li>1998-2005: Tốt nghiệp Bác sĩ Đa khoa &#8211;  Đại học Y Dược</li>\n<li>2005-2008: Hoàn thành khóa học Phẫu thuật tạo hình thẩm mỹ &#8211; Hiệp hội thẩm mỹ Hàn Quốc KCCS</li>\n<li>2008-2009: Hoàn thành khóa học Phẫu thuật nâng ngực &#8211; Tập đoàn Coco Plastic Hàn Quốc</li>\n<li>2009-2012: Hoàn thành khóa học Phẫu thuật Hút mỡ tạo hình tại Đại học  Y Hà Nội </li>\n<li>2012- 2019: Bác sĩ phẫu thuật thẩm mỹ tạo hình vóc dáng tại Bệnh viện Đa khoa Hồng Hà</li>\n<li>2019-nay: Bác sĩ phẫu thuật thẩm mỹ tạo hình vóc dáng tại Bệnh viện Thẩm mỹ Đông Á</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--3"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">kinh nghiệm làm việc</span>\n    </li>\n<li>7 năm kinh nghiệm trong lĩnh vực ngoại khoa.</li>\n<li>8 năm kinh nghiệm Phẫu thuật thẩm mỹ tạo hình vóc dáng.</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--4"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">các dịch vụ thẩm mỹ thực hiện</span>\n    </li>\n<li>Phẫu thuật Nâng ngực bằng phương pháp nội soi.</li>\n<li>Phẫu tthuật treo sa trễ, cắt tuyến vú, thu nhỏ quầng vú, đầu ti.</li>\n<li>Hút mỡ và Phẫu thuật tạo hình thành bụng bằng phương pháp siêu âm.</li>\n<li>Phẫu thuật cấy mỡ toàn mặt + căng chỉ trẻ hóa khuôn mặt toàn diện.</li>\n<li>Phẫu thuật tạo hình môi: Phẫu thuật cắt niêm mạc vùng hàm môi trên điều trị cười hở lợi, Tạo hình môi trái tim, sa trễ môi dưới.</li>\n<li>Phẫu thuật thẩm mỹ vùng kín.</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--1"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">văn bằng chứng chỉ</span>\n    </li>\n<li>Chứng chỉ thẩm mỹ do Hiệp hội thẩm mỹ Hàn Quốc cấp.</li>\n</ul>\n',
    },
    {
        id: "6",
        name: "TS.BS David Lee",
        position:
            " Bác sĩ Phẫu thuật Tạo hình Thẩm mỹ cấp cao - Trưởng khoa Phẫu thuật Thẩm mỹ tại Bệnh viện Thẩm mỹ Đông Á (Hà Nội)",
        image:
            "https://benhvienthammydonga.vn/wp-content/uploads/2023/02/bs-david-lee.png",
        category: "Phẫu thuật thẩm mỹ",
        showHome: "true",
        imageRegion: "none",
        description:
            "<ul>\n<li>Thành viên thuộc Hiệp hội thẩm mỹ Hàn Quốc (ISAPS).</li>\n<li>Hội viên chính hội Phẫu thuật Thẩm mỹ Chỉnh hình Hàn Quốc.</li>\n</ul>\n",
        dataModal:
            '<ul>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--1"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">chức vụ</span>\n    </li>\n<li>Bác sĩ Phẫu thuật Tạo hình Thẩm mỹ cấp cao &#8211; Trưởng khoa Phẫu thuật Thẩm mỹ tại Bệnh viện Thẩm mỹ Đông Á (Hà Nội).</li>\n<li>Thành viên thuộc Hiệp hội thẩm mỹ Hàn Quốc (ISAPS).</li>\n<li>Hội viên chính hội Phẫu thuật Thẩm mỹ Chỉnh hình Hàn Quốc.</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--2"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">quá trình học tập và công tác</span>\n    </li>\n<li>Tốt nghiệp Tốt nghiệp Bác sĩ Đa khoa &#8211; Đại học Y Thái Bình.</li>\n<li>Hoàn thành khóa học Hoàn thành khóa học Phẫu thuật thẩm mỹ gương mặt tại Đại học Y Hà Nội .</li>\n<li>Hoàn thành khóa học phẫu thuật thẩm mỹ tạo hình tại Tập đoàn Coco Plastic Surgery (Hàn Quốc).</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--3"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">kinh nghiệm làm việc</span>\n    </li>\n<li>8 năm kinh nghiệm trong lĩnh vực ngoại khoa</li>\n<li>10 năm kinh nghiệm Phẫu thuật tạo hình thẩm mỹ gương mặt</li>\n<li>10 năm kinh nghiệm Phẫu thuật nâng mũi, cắt mí, nâng ngực, hút mỡ</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--4"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">các dịch vụ thẩm mỹ thực hiện</span>\n    </li>\n<li>Phẫu thuật cắt mí, phẫu thuật nâng mũi, sửa mũi hỏng, mũi dị tật bẩm sinh.</li>\n<li>Phẫu thuật Nâng ngực bằng phương pháp nội soi.</li>\n<li>Phẫu thuật treo sa trễ, cắt tuyến vú, thu nhỏ quầng vú, đầu ti.</li>\n</ul>\n',
    },
    {
        id: "7",
        name: "BS Huỳnh Tuyết Như",
        position: " BS Điều trị nám - tàn nhang công nghệ cao",
        image:
            "https://benhvienthammydonga.vn/wp-content/uploads/2023/02/bs-huynh-tuyet-nhu.png",
        category: "Điều trị - Trẻ hóa da",
        showHome: "false",
        imageRegion: "none",
        description:
            "<ul>\n<li>BS Điều trị nám &#8211; tàn nhang công nghệ cao</li>\n<li>Thạc sĩ – Bác sĩ chuyên ngành da liễu cấp cao</li>\n</ul>\n",
        dataModal:
            '<ul>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--1"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">chức vụ</span>\n    </li>\n<li>BS Điều trị nám &#8211; tàn nhang công nghệ cao</li>\n<li>Thạc sĩ – Bác sĩ chuyên ngành da liễu cấp cao</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--2"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">quá trình học tập và công tác</span>\n    </li>\n<li>Tốt nghiệp trường đại học Y dược HCM</li>\n<li class="popupdoctor_da_1_0_0__name">\n        <span class="popupdoctor_da_1_0_0__icon popupdoctor_da_1_0_0__icon--3"></span><br />\n        <span class="popupdoctor_da_1_0_0__titleName">kinh nghiệm làm việc</span>\n    </li>\n<li>Có 20 năm kinh nghiệm trong lĩnh vực điều trị da</li>\n</ul>\n',
    },
];